# -*- coding: utf-8 -*-
"""Pybrain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xs7UCl6N6a8w_zkgL4Q9rxpqvlFJwwKZ
"""

# Установка библиотек в Colab
!pip install pybrain3
!pip install scipy
!pip install numpy
!pip install tqdm

import sys
import numpy as np
from tqdm import tqdm
import time
# Костыль для починки PyBrain3
sys.modules["scipy.random"] = np.random

from pybrain3.tools.shortcuts import buildNetwork
from pybrain3.datasets import SupervisedDataSet
from pybrain3.supervised.trainers import BackpropTrainer

import matplotlib.pyplot as plt

the_dataset=SupervisedDataSet(2,1) # Создаём датасет

# Набор моделей для обучения
model_XOR=[
    [(0,0), (0)],
    [(0,1), (1)],
    [(1,0), (1)],
    [(1,1), (0)]
]

model_AND=[
    [(0,0), (0,)],
    [(0,1), (0,)],
    [(1,0), (0,)],
    [(1,1), (1,)]
]

model_OR=[
    [(0,0), (0,)],
    [(0,1), (1,)],
    [(1,0), (1,)],
    [(1,1), (1,)]
]

# Быстрый выбор модели
current_model=model_XOR

# Заполняем датасет, используя модель
for input, target in tqdm(current_model):
    the_dataset.addSample(input, target)
    time.sleep(0.5)

# Генерируем нейросеть (2 входа, 3 скрытых слоя, 1 выходной нейрон)
the_network=buildNetwork(2,3,1)
trainer=BackpropTrainer(the_network, the_dataset)
# 🦄 Progress bar(In future)
# Пустой список для значений ошибок
training_values=[]

for epoch in tqdm(range(10000)):
    training_values.append(trainer.train())

for value in enumerate(training_values):
    print(value)

plt.plot(training_values)
plt.show()

print(np.round(the_network.activate([0,0])))
print(np.round(the_network.activate([0,1])))
print(np.round(the_network.activate([1,0])))
print(np.round(the_network.activate([1,1])))

